### ISSUE TITLE
Demo returns 404

### ISSUE THREAD

**Issue by d2x** [t00m/KB4IT#64]
Your projects demo URL is a 404

[t00m.github.io/KB4IT/demo](https://t00m.github.io/KB4IT/demo)

**Comment by t00m** [comment]
Hi @d2x ,

Yes, sorry. I am moving demos to another [repository](https://github.com/t00m/kb4it-adocs).
Right now, there is only [one](https://t00m.github.io/kb4it-adocs/python/) using the theme _snippets_.

I'll try to upload more demos during the next month as soon as I fix some things in the code.
I keep the issue open until I can upload the proper demo..

Thank you for your comment.

**Comment by t00m** [comment]
Hi,

added Awesome-Selfhosted demo app in tests directory. Output [here](https://t00m.github.io/kb4it-adocs/awesome-selfhosted/index.html) in [kb4it-adoc](https://github.com/t00m/kb4it-adocs) repository.

Commits 2d88fecb012e501587588707b6cb03c3b1efd10d and 198eb97cef424dcb1317743a2f9696e1b1e67c9b fix this issue.

Thank you.
